/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as StoreRouteImport } from './routes/store'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ConductRouteImport } from './routes/conduct'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSubscribeRouteImport } from './routes/store.subscribe'
import { Route as StoreIdRouteImport } from './routes/store.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content'
import { Route as AuthenticatedCohostApplyRouteImport } from './routes/_authenticated/cohost-apply'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedContentNewRouteImport } from './routes/_authenticated/content.new'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedAdminVenueComplianceRemindersRouteImport } from './routes/_authenticated/admin.venue-compliance-reminders'
import { Route as AuthenticatedAdminVenueComplianceRouteImport } from './routes/_authenticated/admin.venue-compliance'
import { Route as AuthenticatedAdminSystemLogsRouteImport } from './routes/_authenticated/admin.system-logs'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSafetyIncidentsRouteImport } from './routes/_authenticated/admin.safety-incidents'
import { Route as AuthenticatedAdminLifetimeRouteImport } from './routes/_authenticated/admin.lifetime'
import { Route as AuthenticatedAdminHealthRemindersRouteImport } from './routes/_authenticated/admin.health-reminders'
import { Route as AuthenticatedAdminHealthPurgeRouteImport } from './routes/_authenticated/admin.health-purge'
import { Route as AuthenticatedAdminGoLiveRouteImport } from './routes/_authenticated/admin.go-live'
import { Route as AuthenticatedAdminEventsComplianceRouteImport } from './routes/_authenticated/admin.events-compliance'
import { Route as AuthenticatedAdminEmailSetupRouteImport } from './routes/_authenticated/admin.email-setup'
import { Route as AuthenticatedAdminEmailRecipientSearchRouteImport } from './routes/_authenticated/admin.email-recipient-search'
import { Route as AuthenticatedAdminEmailDeliveryRouteImport } from './routes/_authenticated/admin.email-delivery'
import { Route as AuthenticatedAdminCompliancePolicyRouteImport } from './routes/_authenticated/admin.compliance-policy'
import { Route as AuthenticatedAdminComplianceAuditRouteImport } from './routes/_authenticated/admin.compliance-audit'
import { Route as AuthenticatedAdminCohostsRouteImport } from './routes/_authenticated/admin.cohosts'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksVenueComplianceRemindersRouteImport } from './routes/api/public/hooks/venue-compliance-reminders'
import { Route as ApiPublicHooksTestReminderEmailRouteImport } from './routes/api/public/hooks/test-reminder-email'
import { Route as ApiPublicHooksReminderRetriesRouteImport } from './routes/api/public/hooks/reminder-retries'
import { Route as ApiPublicHooksPreviewReminderEmailRouteImport } from './routes/api/public/hooks/preview-reminder-email'
import { Route as ApiPublicHooksPreviewPortalLinkRouteImport } from './routes/api/public/hooks/preview-portal-link'
import { Route as ApiPublicHooksHealthScreeningRemindersRouteImport } from './routes/api/public/hooks/health-screening-reminders'
import { Route as ApiPublicHooksCronHealthCheckRouteImport } from './routes/api/public/hooks/cron-health-check'
import { Route as ApiPublicDevVerifyAudCheckoutsRouteImport } from './routes/api/public/dev/verify-aud-checkouts'
import { Route as AuthenticatedEventsIdWaiversRouteImport } from './routes/_authenticated/events.$id.waivers'
import { Route as AuthenticatedEventsIdEditRouteImport } from './routes/_authenticated/events.$id.edit'
import { Route as AuthenticatedEventsIdCheckinRouteImport } from './routes/_authenticated/events.$id.checkin'
import { Route as AuthenticatedEventsIdCheckinPrintRouteImport } from './routes/_authenticated/events.$id.checkin.print'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductRoute = ConductRouteImport.update({
  id: '/conduct',
  path: '/conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSubscribeRoute = StoreSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => StoreRoute,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoreRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCohostApplyRoute =
  AuthenticatedCohostApplyRouteImport.update({
    id: '/cohost-apply',
    path: '/cohost-apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentNewRoute = AuthenticatedContentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedContentRoute,
} as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/admin/verifications',
    path: '/admin/verifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVenueComplianceRemindersRoute =
  AuthenticatedAdminVenueComplianceRemindersRouteImport.update({
    id: '/admin/venue-compliance-reminders',
    path: '/admin/venue-compliance-reminders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVenueComplianceRoute =
  AuthenticatedAdminVenueComplianceRouteImport.update({
    id: '/admin/venue-compliance',
    path: '/admin/venue-compliance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSystemLogsRoute =
  AuthenticatedAdminSystemLogsRouteImport.update({
    id: '/admin/system-logs',
    path: '/admin/system-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSafetyIncidentsRoute =
  AuthenticatedAdminSafetyIncidentsRouteImport.update({
    id: '/admin/safety-incidents',
    path: '/admin/safety-incidents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLifetimeRoute =
  AuthenticatedAdminLifetimeRouteImport.update({
    id: '/admin/lifetime',
    path: '/admin/lifetime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHealthRemindersRoute =
  AuthenticatedAdminHealthRemindersRouteImport.update({
    id: '/admin/health-reminders',
    path: '/admin/health-reminders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHealthPurgeRoute =
  AuthenticatedAdminHealthPurgeRouteImport.update({
    id: '/admin/health-purge',
    path: '/admin/health-purge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGoLiveRoute =
  AuthenticatedAdminGoLiveRouteImport.update({
    id: '/admin/go-live',
    path: '/admin/go-live',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEventsComplianceRoute =
  AuthenticatedAdminEventsComplianceRouteImport.update({
    id: '/admin/events-compliance',
    path: '/admin/events-compliance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailSetupRoute =
  AuthenticatedAdminEmailSetupRouteImport.update({
    id: '/admin/email-setup',
    path: '/admin/email-setup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailRecipientSearchRoute =
  AuthenticatedAdminEmailRecipientSearchRouteImport.update({
    id: '/admin/email-recipient-search',
    path: '/admin/email-recipient-search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailDeliveryRoute =
  AuthenticatedAdminEmailDeliveryRouteImport.update({
    id: '/admin/email-delivery',
    path: '/admin/email-delivery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCompliancePolicyRoute =
  AuthenticatedAdminCompliancePolicyRouteImport.update({
    id: '/admin/compliance-policy',
    path: '/admin/compliance-policy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplianceAuditRoute =
  AuthenticatedAdminComplianceAuditRouteImport.update({
    id: '/admin/compliance-audit',
    path: '/admin/compliance-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCohostsRoute =
  AuthenticatedAdminCohostsRouteImport.update({
    id: '/admin/cohosts',
    path: '/admin/cohosts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVenueComplianceRemindersRoute =
  ApiPublicHooksVenueComplianceRemindersRouteImport.update({
    id: '/api/public/hooks/venue-compliance-reminders',
    path: '/api/public/hooks/venue-compliance-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTestReminderEmailRoute =
  ApiPublicHooksTestReminderEmailRouteImport.update({
    id: '/api/public/hooks/test-reminder-email',
    path: '/api/public/hooks/test-reminder-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReminderRetriesRoute =
  ApiPublicHooksReminderRetriesRouteImport.update({
    id: '/api/public/hooks/reminder-retries',
    path: '/api/public/hooks/reminder-retries',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPreviewReminderEmailRoute =
  ApiPublicHooksPreviewReminderEmailRouteImport.update({
    id: '/api/public/hooks/preview-reminder-email',
    path: '/api/public/hooks/preview-reminder-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPreviewPortalLinkRoute =
  ApiPublicHooksPreviewPortalLinkRouteImport.update({
    id: '/api/public/hooks/preview-portal-link',
    path: '/api/public/hooks/preview-portal-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthScreeningRemindersRoute =
  ApiPublicHooksHealthScreeningRemindersRouteImport.update({
    id: '/api/public/hooks/health-screening-reminders',
    path: '/api/public/hooks/health-screening-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCronHealthCheckRoute =
  ApiPublicHooksCronHealthCheckRouteImport.update({
    id: '/api/public/hooks/cron-health-check',
    path: '/api/public/hooks/cron-health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevVerifyAudCheckoutsRoute =
  ApiPublicDevVerifyAudCheckoutsRouteImport.update({
    id: '/api/public/dev/verify-aud-checkouts',
    path: '/api/public/dev/verify-aud-checkouts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEventsIdWaiversRoute =
  AuthenticatedEventsIdWaiversRouteImport.update({
    id: '/events/$id/waivers',
    path: '/events/$id/waivers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdEditRoute =
  AuthenticatedEventsIdEditRouteImport.update({
    id: '/events/$id/edit',
    path: '/events/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdCheckinRoute =
  AuthenticatedEventsIdCheckinRouteImport.update({
    id: '/events/$id/checkin',
    path: '/events/$id/checkin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdCheckinPrintRoute =
  AuthenticatedEventsIdCheckinPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => AuthenticatedEventsIdCheckinRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/conduct': typeof ConductRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/store': typeof StoreRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/cohost-apply': typeof AuthenticatedCohostApplyRoute
  '/content': typeof AuthenticatedContentRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/support': typeof AuthenticatedSupportRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/api/chat': typeof ApiChatRoute
  '/events/$id': typeof EventsIdRoute
  '/store/$id': typeof StoreIdRoute
  '/store/subscribe': typeof StoreSubscribeRoute
  '/admin/cohosts': typeof AuthenticatedAdminCohostsRoute
  '/admin/compliance-audit': typeof AuthenticatedAdminComplianceAuditRoute
  '/admin/compliance-policy': typeof AuthenticatedAdminCompliancePolicyRoute
  '/admin/email-delivery': typeof AuthenticatedAdminEmailDeliveryRoute
  '/admin/email-recipient-search': typeof AuthenticatedAdminEmailRecipientSearchRoute
  '/admin/email-setup': typeof AuthenticatedAdminEmailSetupRoute
  '/admin/events-compliance': typeof AuthenticatedAdminEventsComplianceRoute
  '/admin/go-live': typeof AuthenticatedAdminGoLiveRoute
  '/admin/health-purge': typeof AuthenticatedAdminHealthPurgeRoute
  '/admin/health-reminders': typeof AuthenticatedAdminHealthRemindersRoute
  '/admin/lifetime': typeof AuthenticatedAdminLifetimeRoute
  '/admin/safety-incidents': typeof AuthenticatedAdminSafetyIncidentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/system-logs': typeof AuthenticatedAdminSystemLogsRoute
  '/admin/venue-compliance': typeof AuthenticatedAdminVenueComplianceRoute
  '/admin/venue-compliance-reminders': typeof AuthenticatedAdminVenueComplianceRemindersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/content/new': typeof AuthenticatedContentNewRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/events/$id/checkin': typeof AuthenticatedEventsIdCheckinRouteWithChildren
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/events/$id/waivers': typeof AuthenticatedEventsIdWaiversRoute
  '/api/public/dev/verify-aud-checkouts': typeof ApiPublicDevVerifyAudCheckoutsRoute
  '/api/public/hooks/cron-health-check': typeof ApiPublicHooksCronHealthCheckRoute
  '/api/public/hooks/health-screening-reminders': typeof ApiPublicHooksHealthScreeningRemindersRoute
  '/api/public/hooks/preview-portal-link': typeof ApiPublicHooksPreviewPortalLinkRoute
  '/api/public/hooks/preview-reminder-email': typeof ApiPublicHooksPreviewReminderEmailRoute
  '/api/public/hooks/reminder-retries': typeof ApiPublicHooksReminderRetriesRoute
  '/api/public/hooks/test-reminder-email': typeof ApiPublicHooksTestReminderEmailRoute
  '/api/public/hooks/venue-compliance-reminders': typeof ApiPublicHooksVenueComplianceRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/events/$id/checkin/print': typeof AuthenticatedEventsIdCheckinPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/conduct': typeof ConductRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/store': typeof StoreRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/cohost-apply': typeof AuthenticatedCohostApplyRoute
  '/content': typeof AuthenticatedContentRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/support': typeof AuthenticatedSupportRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/api/chat': typeof ApiChatRoute
  '/events/$id': typeof EventsIdRoute
  '/store/$id': typeof StoreIdRoute
  '/store/subscribe': typeof StoreSubscribeRoute
  '/admin/cohosts': typeof AuthenticatedAdminCohostsRoute
  '/admin/compliance-audit': typeof AuthenticatedAdminComplianceAuditRoute
  '/admin/compliance-policy': typeof AuthenticatedAdminCompliancePolicyRoute
  '/admin/email-delivery': typeof AuthenticatedAdminEmailDeliveryRoute
  '/admin/email-recipient-search': typeof AuthenticatedAdminEmailRecipientSearchRoute
  '/admin/email-setup': typeof AuthenticatedAdminEmailSetupRoute
  '/admin/events-compliance': typeof AuthenticatedAdminEventsComplianceRoute
  '/admin/go-live': typeof AuthenticatedAdminGoLiveRoute
  '/admin/health-purge': typeof AuthenticatedAdminHealthPurgeRoute
  '/admin/health-reminders': typeof AuthenticatedAdminHealthRemindersRoute
  '/admin/lifetime': typeof AuthenticatedAdminLifetimeRoute
  '/admin/safety-incidents': typeof AuthenticatedAdminSafetyIncidentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/system-logs': typeof AuthenticatedAdminSystemLogsRoute
  '/admin/venue-compliance': typeof AuthenticatedAdminVenueComplianceRoute
  '/admin/venue-compliance-reminders': typeof AuthenticatedAdminVenueComplianceRemindersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/content/new': typeof AuthenticatedContentNewRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/events/$id/checkin': typeof AuthenticatedEventsIdCheckinRouteWithChildren
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/events/$id/waivers': typeof AuthenticatedEventsIdWaiversRoute
  '/api/public/dev/verify-aud-checkouts': typeof ApiPublicDevVerifyAudCheckoutsRoute
  '/api/public/hooks/cron-health-check': typeof ApiPublicHooksCronHealthCheckRoute
  '/api/public/hooks/health-screening-reminders': typeof ApiPublicHooksHealthScreeningRemindersRoute
  '/api/public/hooks/preview-portal-link': typeof ApiPublicHooksPreviewPortalLinkRoute
  '/api/public/hooks/preview-reminder-email': typeof ApiPublicHooksPreviewReminderEmailRoute
  '/api/public/hooks/reminder-retries': typeof ApiPublicHooksReminderRetriesRoute
  '/api/public/hooks/test-reminder-email': typeof ApiPublicHooksTestReminderEmailRoute
  '/api/public/hooks/venue-compliance-reminders': typeof ApiPublicHooksVenueComplianceRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/events/$id/checkin/print': typeof AuthenticatedEventsIdCheckinPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/compliance': typeof ComplianceRoute
  '/conduct': typeof ConductRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/store': typeof StoreRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_authenticated/cohost-apply': typeof AuthenticatedCohostApplyRoute
  '/_authenticated/content': typeof AuthenticatedContentRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/api/chat': typeof ApiChatRoute
  '/events/$id': typeof EventsIdRoute
  '/store/$id': typeof StoreIdRoute
  '/store/subscribe': typeof StoreSubscribeRoute
  '/_authenticated/admin/cohosts': typeof AuthenticatedAdminCohostsRoute
  '/_authenticated/admin/compliance-audit': typeof AuthenticatedAdminComplianceAuditRoute
  '/_authenticated/admin/compliance-policy': typeof AuthenticatedAdminCompliancePolicyRoute
  '/_authenticated/admin/email-delivery': typeof AuthenticatedAdminEmailDeliveryRoute
  '/_authenticated/admin/email-recipient-search': typeof AuthenticatedAdminEmailRecipientSearchRoute
  '/_authenticated/admin/email-setup': typeof AuthenticatedAdminEmailSetupRoute
  '/_authenticated/admin/events-compliance': typeof AuthenticatedAdminEventsComplianceRoute
  '/_authenticated/admin/go-live': typeof AuthenticatedAdminGoLiveRoute
  '/_authenticated/admin/health-purge': typeof AuthenticatedAdminHealthPurgeRoute
  '/_authenticated/admin/health-reminders': typeof AuthenticatedAdminHealthRemindersRoute
  '/_authenticated/admin/lifetime': typeof AuthenticatedAdminLifetimeRoute
  '/_authenticated/admin/safety-incidents': typeof AuthenticatedAdminSafetyIncidentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/system-logs': typeof AuthenticatedAdminSystemLogsRoute
  '/_authenticated/admin/venue-compliance': typeof AuthenticatedAdminVenueComplianceRoute
  '/_authenticated/admin/venue-compliance-reminders': typeof AuthenticatedAdminVenueComplianceRemindersRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/content/new': typeof AuthenticatedContentNewRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/events/$id/checkin': typeof AuthenticatedEventsIdCheckinRouteWithChildren
  '/_authenticated/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/_authenticated/events/$id/waivers': typeof AuthenticatedEventsIdWaiversRoute
  '/api/public/dev/verify-aud-checkouts': typeof ApiPublicDevVerifyAudCheckoutsRoute
  '/api/public/hooks/cron-health-check': typeof ApiPublicHooksCronHealthCheckRoute
  '/api/public/hooks/health-screening-reminders': typeof ApiPublicHooksHealthScreeningRemindersRoute
  '/api/public/hooks/preview-portal-link': typeof ApiPublicHooksPreviewPortalLinkRoute
  '/api/public/hooks/preview-reminder-email': typeof ApiPublicHooksPreviewReminderEmailRoute
  '/api/public/hooks/reminder-retries': typeof ApiPublicHooksReminderRetriesRoute
  '/api/public/hooks/test-reminder-email': typeof ApiPublicHooksTestReminderEmailRoute
  '/api/public/hooks/venue-compliance-reminders': typeof ApiPublicHooksVenueComplianceRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/events/$id/checkin/print': typeof AuthenticatedEventsIdCheckinPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compliance'
    | '/conduct'
    | '/legal'
    | '/privacy'
    | '/store'
    | '/unlock'
    | '/cohost-apply'
    | '/content'
    | '/dashboard'
    | '/library'
    | '/support'
    | '/verify'
    | '/api/chat'
    | '/events/$id'
    | '/store/$id'
    | '/store/subscribe'
    | '/admin/cohosts'
    | '/admin/compliance-audit'
    | '/admin/compliance-policy'
    | '/admin/email-delivery'
    | '/admin/email-recipient-search'
    | '/admin/email-setup'
    | '/admin/events-compliance'
    | '/admin/go-live'
    | '/admin/health-purge'
    | '/admin/health-reminders'
    | '/admin/lifetime'
    | '/admin/safety-incidents'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/system-logs'
    | '/admin/venue-compliance'
    | '/admin/venue-compliance-reminders'
    | '/admin/verifications'
    | '/content/new'
    | '/events/new'
    | '/events/$id/checkin'
    | '/events/$id/edit'
    | '/events/$id/waivers'
    | '/api/public/dev/verify-aud-checkouts'
    | '/api/public/hooks/cron-health-check'
    | '/api/public/hooks/health-screening-reminders'
    | '/api/public/hooks/preview-portal-link'
    | '/api/public/hooks/preview-reminder-email'
    | '/api/public/hooks/reminder-retries'
    | '/api/public/hooks/test-reminder-email'
    | '/api/public/hooks/venue-compliance-reminders'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/events/$id/checkin/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compliance'
    | '/conduct'
    | '/legal'
    | '/privacy'
    | '/store'
    | '/unlock'
    | '/cohost-apply'
    | '/content'
    | '/dashboard'
    | '/library'
    | '/support'
    | '/verify'
    | '/api/chat'
    | '/events/$id'
    | '/store/$id'
    | '/store/subscribe'
    | '/admin/cohosts'
    | '/admin/compliance-audit'
    | '/admin/compliance-policy'
    | '/admin/email-delivery'
    | '/admin/email-recipient-search'
    | '/admin/email-setup'
    | '/admin/events-compliance'
    | '/admin/go-live'
    | '/admin/health-purge'
    | '/admin/health-reminders'
    | '/admin/lifetime'
    | '/admin/safety-incidents'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/system-logs'
    | '/admin/venue-compliance'
    | '/admin/venue-compliance-reminders'
    | '/admin/verifications'
    | '/content/new'
    | '/events/new'
    | '/events/$id/checkin'
    | '/events/$id/edit'
    | '/events/$id/waivers'
    | '/api/public/dev/verify-aud-checkouts'
    | '/api/public/hooks/cron-health-check'
    | '/api/public/hooks/health-screening-reminders'
    | '/api/public/hooks/preview-portal-link'
    | '/api/public/hooks/preview-reminder-email'
    | '/api/public/hooks/reminder-retries'
    | '/api/public/hooks/test-reminder-email'
    | '/api/public/hooks/venue-compliance-reminders'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/events/$id/checkin/print'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/compliance'
    | '/conduct'
    | '/legal'
    | '/privacy'
    | '/store'
    | '/unlock'
    | '/_authenticated/cohost-apply'
    | '/_authenticated/content'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/support'
    | '/_authenticated/verify'
    | '/api/chat'
    | '/events/$id'
    | '/store/$id'
    | '/store/subscribe'
    | '/_authenticated/admin/cohosts'
    | '/_authenticated/admin/compliance-audit'
    | '/_authenticated/admin/compliance-policy'
    | '/_authenticated/admin/email-delivery'
    | '/_authenticated/admin/email-recipient-search'
    | '/_authenticated/admin/email-setup'
    | '/_authenticated/admin/events-compliance'
    | '/_authenticated/admin/go-live'
    | '/_authenticated/admin/health-purge'
    | '/_authenticated/admin/health-reminders'
    | '/_authenticated/admin/lifetime'
    | '/_authenticated/admin/safety-incidents'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/system-logs'
    | '/_authenticated/admin/venue-compliance'
    | '/_authenticated/admin/venue-compliance-reminders'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/content/new'
    | '/_authenticated/events/new'
    | '/_authenticated/events/$id/checkin'
    | '/_authenticated/events/$id/edit'
    | '/_authenticated/events/$id/waivers'
    | '/api/public/dev/verify-aud-checkouts'
    | '/api/public/hooks/cron-health-check'
    | '/api/public/hooks/health-screening-reminders'
    | '/api/public/hooks/preview-portal-link'
    | '/api/public/hooks/preview-reminder-email'
    | '/api/public/hooks/reminder-retries'
    | '/api/public/hooks/test-reminder-email'
    | '/api/public/hooks/venue-compliance-reminders'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/events/$id/checkin/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComplianceRoute: typeof ComplianceRoute
  ConductRoute: typeof ConductRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  StoreRoute: typeof StoreRouteWithChildren
  UnlockRoute: typeof UnlockRoute
  ApiChatRoute: typeof ApiChatRoute
  EventsIdRoute: typeof EventsIdRoute
  ApiPublicDevVerifyAudCheckoutsRoute: typeof ApiPublicDevVerifyAudCheckoutsRoute
  ApiPublicHooksCronHealthCheckRoute: typeof ApiPublicHooksCronHealthCheckRoute
  ApiPublicHooksHealthScreeningRemindersRoute: typeof ApiPublicHooksHealthScreeningRemindersRoute
  ApiPublicHooksPreviewPortalLinkRoute: typeof ApiPublicHooksPreviewPortalLinkRoute
  ApiPublicHooksPreviewReminderEmailRoute: typeof ApiPublicHooksPreviewReminderEmailRoute
  ApiPublicHooksReminderRetriesRoute: typeof ApiPublicHooksReminderRetriesRoute
  ApiPublicHooksTestReminderEmailRoute: typeof ApiPublicHooksTestReminderEmailRoute
  ApiPublicHooksVenueComplianceRemindersRoute: typeof ApiPublicHooksVenueComplianceRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conduct': {
      id: '/conduct'
      path: '/conduct'
      fullPath: '/conduct'
      preLoaderRoute: typeof ConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/subscribe': {
      id: '/store/subscribe'
      path: '/subscribe'
      fullPath: '/store/subscribe'
      preLoaderRoute: typeof StoreSubscribeRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cohost-apply': {
      id: '/_authenticated/cohost-apply'
      path: '/cohost-apply'
      fullPath: '/cohost-apply'
      preLoaderRoute: typeof AuthenticatedCohostApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/new': {
      id: '/_authenticated/content/new'
      path: '/new'
      fullPath: '/content/new'
      preLoaderRoute: typeof AuthenticatedContentNewRouteImport
      parentRoute: typeof AuthenticatedContentRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/venue-compliance-reminders': {
      id: '/_authenticated/admin/venue-compliance-reminders'
      path: '/admin/venue-compliance-reminders'
      fullPath: '/admin/venue-compliance-reminders'
      preLoaderRoute: typeof AuthenticatedAdminVenueComplianceRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/venue-compliance': {
      id: '/_authenticated/admin/venue-compliance'
      path: '/admin/venue-compliance'
      fullPath: '/admin/venue-compliance'
      preLoaderRoute: typeof AuthenticatedAdminVenueComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/system-logs': {
      id: '/_authenticated/admin/system-logs'
      path: '/admin/system-logs'
      fullPath: '/admin/system-logs'
      preLoaderRoute: typeof AuthenticatedAdminSystemLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/safety-incidents': {
      id: '/_authenticated/admin/safety-incidents'
      path: '/admin/safety-incidents'
      fullPath: '/admin/safety-incidents'
      preLoaderRoute: typeof AuthenticatedAdminSafetyIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/lifetime': {
      id: '/_authenticated/admin/lifetime'
      path: '/admin/lifetime'
      fullPath: '/admin/lifetime'
      preLoaderRoute: typeof AuthenticatedAdminLifetimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/health-reminders': {
      id: '/_authenticated/admin/health-reminders'
      path: '/admin/health-reminders'
      fullPath: '/admin/health-reminders'
      preLoaderRoute: typeof AuthenticatedAdminHealthRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/health-purge': {
      id: '/_authenticated/admin/health-purge'
      path: '/admin/health-purge'
      fullPath: '/admin/health-purge'
      preLoaderRoute: typeof AuthenticatedAdminHealthPurgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/go-live': {
      id: '/_authenticated/admin/go-live'
      path: '/admin/go-live'
      fullPath: '/admin/go-live'
      preLoaderRoute: typeof AuthenticatedAdminGoLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/events-compliance': {
      id: '/_authenticated/admin/events-compliance'
      path: '/admin/events-compliance'
      fullPath: '/admin/events-compliance'
      preLoaderRoute: typeof AuthenticatedAdminEventsComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-setup': {
      id: '/_authenticated/admin/email-setup'
      path: '/admin/email-setup'
      fullPath: '/admin/email-setup'
      preLoaderRoute: typeof AuthenticatedAdminEmailSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-recipient-search': {
      id: '/_authenticated/admin/email-recipient-search'
      path: '/admin/email-recipient-search'
      fullPath: '/admin/email-recipient-search'
      preLoaderRoute: typeof AuthenticatedAdminEmailRecipientSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-delivery': {
      id: '/_authenticated/admin/email-delivery'
      path: '/admin/email-delivery'
      fullPath: '/admin/email-delivery'
      preLoaderRoute: typeof AuthenticatedAdminEmailDeliveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance-policy': {
      id: '/_authenticated/admin/compliance-policy'
      path: '/admin/compliance-policy'
      fullPath: '/admin/compliance-policy'
      preLoaderRoute: typeof AuthenticatedAdminCompliancePolicyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/compliance-audit': {
      id: '/_authenticated/admin/compliance-audit'
      path: '/admin/compliance-audit'
      fullPath: '/admin/compliance-audit'
      preLoaderRoute: typeof AuthenticatedAdminComplianceAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cohosts': {
      id: '/_authenticated/admin/cohosts'
      path: '/admin/cohosts'
      fullPath: '/admin/cohosts'
      preLoaderRoute: typeof AuthenticatedAdminCohostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/venue-compliance-reminders': {
      id: '/api/public/hooks/venue-compliance-reminders'
      path: '/api/public/hooks/venue-compliance-reminders'
      fullPath: '/api/public/hooks/venue-compliance-reminders'
      preLoaderRoute: typeof ApiPublicHooksVenueComplianceRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/test-reminder-email': {
      id: '/api/public/hooks/test-reminder-email'
      path: '/api/public/hooks/test-reminder-email'
      fullPath: '/api/public/hooks/test-reminder-email'
      preLoaderRoute: typeof ApiPublicHooksTestReminderEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reminder-retries': {
      id: '/api/public/hooks/reminder-retries'
      path: '/api/public/hooks/reminder-retries'
      fullPath: '/api/public/hooks/reminder-retries'
      preLoaderRoute: typeof ApiPublicHooksReminderRetriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/preview-reminder-email': {
      id: '/api/public/hooks/preview-reminder-email'
      path: '/api/public/hooks/preview-reminder-email'
      fullPath: '/api/public/hooks/preview-reminder-email'
      preLoaderRoute: typeof ApiPublicHooksPreviewReminderEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/preview-portal-link': {
      id: '/api/public/hooks/preview-portal-link'
      path: '/api/public/hooks/preview-portal-link'
      fullPath: '/api/public/hooks/preview-portal-link'
      preLoaderRoute: typeof ApiPublicHooksPreviewPortalLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health-screening-reminders': {
      id: '/api/public/hooks/health-screening-reminders'
      path: '/api/public/hooks/health-screening-reminders'
      fullPath: '/api/public/hooks/health-screening-reminders'
      preLoaderRoute: typeof ApiPublicHooksHealthScreeningRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cron-health-check': {
      id: '/api/public/hooks/cron-health-check'
      path: '/api/public/hooks/cron-health-check'
      fullPath: '/api/public/hooks/cron-health-check'
      preLoaderRoute: typeof ApiPublicHooksCronHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dev/verify-aud-checkouts': {
      id: '/api/public/dev/verify-aud-checkouts'
      path: '/api/public/dev/verify-aud-checkouts'
      fullPath: '/api/public/dev/verify-aud-checkouts'
      preLoaderRoute: typeof ApiPublicDevVerifyAudCheckoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/$id/waivers': {
      id: '/_authenticated/events/$id/waivers'
      path: '/events/$id/waivers'
      fullPath: '/events/$id/waivers'
      preLoaderRoute: typeof AuthenticatedEventsIdWaiversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/edit': {
      id: '/_authenticated/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof AuthenticatedEventsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/checkin': {
      id: '/_authenticated/events/$id/checkin'
      path: '/events/$id/checkin'
      fullPath: '/events/$id/checkin'
      preLoaderRoute: typeof AuthenticatedEventsIdCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/checkin/print': {
      id: '/_authenticated/events/$id/checkin/print'
      path: '/print'
      fullPath: '/events/$id/checkin/print'
      preLoaderRoute: typeof AuthenticatedEventsIdCheckinPrintRouteImport
      parentRoute: typeof AuthenticatedEventsIdCheckinRoute
    }
  }
}

interface AuthenticatedContentRouteChildren {
  AuthenticatedContentNewRoute: typeof AuthenticatedContentNewRoute
}

const AuthenticatedContentRouteChildren: AuthenticatedContentRouteChildren = {
  AuthenticatedContentNewRoute: AuthenticatedContentNewRoute,
}

const AuthenticatedContentRouteWithChildren =
  AuthenticatedContentRoute._addFileChildren(AuthenticatedContentRouteChildren)

interface AuthenticatedEventsIdCheckinRouteChildren {
  AuthenticatedEventsIdCheckinPrintRoute: typeof AuthenticatedEventsIdCheckinPrintRoute
}

const AuthenticatedEventsIdCheckinRouteChildren: AuthenticatedEventsIdCheckinRouteChildren =
  {
    AuthenticatedEventsIdCheckinPrintRoute:
      AuthenticatedEventsIdCheckinPrintRoute,
  }

const AuthenticatedEventsIdCheckinRouteWithChildren =
  AuthenticatedEventsIdCheckinRoute._addFileChildren(
    AuthenticatedEventsIdCheckinRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCohostApplyRoute: typeof AuthenticatedCohostApplyRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
  AuthenticatedAdminCohostsRoute: typeof AuthenticatedAdminCohostsRoute
  AuthenticatedAdminComplianceAuditRoute: typeof AuthenticatedAdminComplianceAuditRoute
  AuthenticatedAdminCompliancePolicyRoute: typeof AuthenticatedAdminCompliancePolicyRoute
  AuthenticatedAdminEmailDeliveryRoute: typeof AuthenticatedAdminEmailDeliveryRoute
  AuthenticatedAdminEmailRecipientSearchRoute: typeof AuthenticatedAdminEmailRecipientSearchRoute
  AuthenticatedAdminEmailSetupRoute: typeof AuthenticatedAdminEmailSetupRoute
  AuthenticatedAdminEventsComplianceRoute: typeof AuthenticatedAdminEventsComplianceRoute
  AuthenticatedAdminGoLiveRoute: typeof AuthenticatedAdminGoLiveRoute
  AuthenticatedAdminHealthPurgeRoute: typeof AuthenticatedAdminHealthPurgeRoute
  AuthenticatedAdminHealthRemindersRoute: typeof AuthenticatedAdminHealthRemindersRoute
  AuthenticatedAdminLifetimeRoute: typeof AuthenticatedAdminLifetimeRoute
  AuthenticatedAdminSafetyIncidentsRoute: typeof AuthenticatedAdminSafetyIncidentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminSystemLogsRoute: typeof AuthenticatedAdminSystemLogsRoute
  AuthenticatedAdminVenueComplianceRoute: typeof AuthenticatedAdminVenueComplianceRoute
  AuthenticatedAdminVenueComplianceRemindersRoute: typeof AuthenticatedAdminVenueComplianceRemindersRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedEventsIdCheckinRoute: typeof AuthenticatedEventsIdCheckinRouteWithChildren
  AuthenticatedEventsIdEditRoute: typeof AuthenticatedEventsIdEditRoute
  AuthenticatedEventsIdWaiversRoute: typeof AuthenticatedEventsIdWaiversRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCohostApplyRoute: AuthenticatedCohostApplyRoute,
  AuthenticatedContentRoute: AuthenticatedContentRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
  AuthenticatedAdminCohostsRoute: AuthenticatedAdminCohostsRoute,
  AuthenticatedAdminComplianceAuditRoute:
    AuthenticatedAdminComplianceAuditRoute,
  AuthenticatedAdminCompliancePolicyRoute:
    AuthenticatedAdminCompliancePolicyRoute,
  AuthenticatedAdminEmailDeliveryRoute: AuthenticatedAdminEmailDeliveryRoute,
  AuthenticatedAdminEmailRecipientSearchRoute:
    AuthenticatedAdminEmailRecipientSearchRoute,
  AuthenticatedAdminEmailSetupRoute: AuthenticatedAdminEmailSetupRoute,
  AuthenticatedAdminEventsComplianceRoute:
    AuthenticatedAdminEventsComplianceRoute,
  AuthenticatedAdminGoLiveRoute: AuthenticatedAdminGoLiveRoute,
  AuthenticatedAdminHealthPurgeRoute: AuthenticatedAdminHealthPurgeRoute,
  AuthenticatedAdminHealthRemindersRoute:
    AuthenticatedAdminHealthRemindersRoute,
  AuthenticatedAdminLifetimeRoute: AuthenticatedAdminLifetimeRoute,
  AuthenticatedAdminSafetyIncidentsRoute:
    AuthenticatedAdminSafetyIncidentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminSystemLogsRoute: AuthenticatedAdminSystemLogsRoute,
  AuthenticatedAdminVenueComplianceRoute:
    AuthenticatedAdminVenueComplianceRoute,
  AuthenticatedAdminVenueComplianceRemindersRoute:
    AuthenticatedAdminVenueComplianceRemindersRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedEventsIdCheckinRoute:
    AuthenticatedEventsIdCheckinRouteWithChildren,
  AuthenticatedEventsIdEditRoute: AuthenticatedEventsIdEditRoute,
  AuthenticatedEventsIdWaiversRoute: AuthenticatedEventsIdWaiversRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StoreRouteChildren {
  StoreIdRoute: typeof StoreIdRoute
  StoreSubscribeRoute: typeof StoreSubscribeRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreIdRoute: StoreIdRoute,
  StoreSubscribeRoute: StoreSubscribeRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComplianceRoute: ComplianceRoute,
  ConductRoute: ConductRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  StoreRoute: StoreRouteWithChildren,
  UnlockRoute: UnlockRoute,
  ApiChatRoute: ApiChatRoute,
  EventsIdRoute: EventsIdRoute,
  ApiPublicDevVerifyAudCheckoutsRoute: ApiPublicDevVerifyAudCheckoutsRoute,
  ApiPublicHooksCronHealthCheckRoute: ApiPublicHooksCronHealthCheckRoute,
  ApiPublicHooksHealthScreeningRemindersRoute:
    ApiPublicHooksHealthScreeningRemindersRoute,
  ApiPublicHooksPreviewPortalLinkRoute: ApiPublicHooksPreviewPortalLinkRoute,
  ApiPublicHooksPreviewReminderEmailRoute:
    ApiPublicHooksPreviewReminderEmailRoute,
  ApiPublicHooksReminderRetriesRoute: ApiPublicHooksReminderRetriesRoute,
  ApiPublicHooksTestReminderEmailRoute: ApiPublicHooksTestReminderEmailRoute,
  ApiPublicHooksVenueComplianceRemindersRoute:
    ApiPublicHooksVenueComplianceRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
