/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as StoreRouteImport } from './routes/store'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSubscribeRouteImport } from './routes/store.subscribe'
import { Route as StoreIdRouteImport } from './routes/store.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedContentNewRouteImport } from './routes/_authenticated/content.new'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminLifetimeRouteImport } from './routes/_authenticated/admin.lifetime'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedEventsIdEditRouteImport } from './routes/_authenticated/events.$id.edit'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSubscribeRoute = StoreSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => StoreRoute,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoreRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentNewRoute = AuthenticatedContentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedContentRoute,
} as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/admin/verifications',
    path: '/admin/verifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLifetimeRoute =
  AuthenticatedAdminLifetimeRouteImport.update({
    id: '/admin/lifetime',
    path: '/admin/lifetime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedEventsIdEditRoute =
  AuthenticatedEventsIdEditRouteImport.update({
    id: '/events/$id/edit',
    path: '/events/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/store': typeof StoreRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/content': typeof AuthenticatedContentRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/events/$id': typeof EventsIdRoute
  '/store/$id': typeof StoreIdRoute
  '/store/subscribe': typeof StoreSubscribeRoute
  '/admin/lifetime': typeof AuthenticatedAdminLifetimeRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/content/new': typeof AuthenticatedContentNewRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/store': typeof StoreRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/content': typeof AuthenticatedContentRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/events/$id': typeof EventsIdRoute
  '/store/$id': typeof StoreIdRoute
  '/store/subscribe': typeof StoreSubscribeRoute
  '/admin/lifetime': typeof AuthenticatedAdminLifetimeRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/content/new': typeof AuthenticatedContentNewRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/store': typeof StoreRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_authenticated/content': typeof AuthenticatedContentRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/events/$id': typeof EventsIdRoute
  '/store/$id': typeof StoreIdRoute
  '/store/subscribe': typeof StoreSubscribeRoute
  '/_authenticated/admin/lifetime': typeof AuthenticatedAdminLifetimeRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/content/new': typeof AuthenticatedContentNewRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/events/$id/edit': typeof AuthenticatedEventsIdEditRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/store'
    | '/unlock'
    | '/content'
    | '/dashboard'
    | '/library'
    | '/verify'
    | '/events/$id'
    | '/store/$id'
    | '/store/subscribe'
    | '/admin/lifetime'
    | '/admin/settings'
    | '/admin/verifications'
    | '/content/new'
    | '/events/new'
    | '/events/$id/edit'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/store'
    | '/unlock'
    | '/content'
    | '/dashboard'
    | '/library'
    | '/verify'
    | '/events/$id'
    | '/store/$id'
    | '/store/subscribe'
    | '/admin/lifetime'
    | '/admin/settings'
    | '/admin/verifications'
    | '/content/new'
    | '/events/new'
    | '/events/$id/edit'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/store'
    | '/unlock'
    | '/_authenticated/content'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/verify'
    | '/events/$id'
    | '/store/$id'
    | '/store/subscribe'
    | '/_authenticated/admin/lifetime'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/content/new'
    | '/_authenticated/events/new'
    | '/_authenticated/events/$id/edit'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  StoreRoute: typeof StoreRouteWithChildren
  UnlockRoute: typeof UnlockRoute
  EventsIdRoute: typeof EventsIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/subscribe': {
      id: '/store/subscribe'
      path: '/subscribe'
      fullPath: '/store/subscribe'
      preLoaderRoute: typeof StoreSubscribeRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/new': {
      id: '/_authenticated/content/new'
      path: '/new'
      fullPath: '/content/new'
      preLoaderRoute: typeof AuthenticatedContentNewRouteImport
      parentRoute: typeof AuthenticatedContentRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/lifetime': {
      id: '/_authenticated/admin/lifetime'
      path: '/admin/lifetime'
      fullPath: '/admin/lifetime'
      preLoaderRoute: typeof AuthenticatedAdminLifetimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/$id/edit': {
      id: '/_authenticated/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof AuthenticatedEventsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedContentRouteChildren {
  AuthenticatedContentNewRoute: typeof AuthenticatedContentNewRoute
}

const AuthenticatedContentRouteChildren: AuthenticatedContentRouteChildren = {
  AuthenticatedContentNewRoute: AuthenticatedContentNewRoute,
}

const AuthenticatedContentRouteWithChildren =
  AuthenticatedContentRoute._addFileChildren(AuthenticatedContentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContentRoute: typeof AuthenticatedContentRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
  AuthenticatedAdminLifetimeRoute: typeof AuthenticatedAdminLifetimeRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedEventsIdEditRoute: typeof AuthenticatedEventsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContentRoute: AuthenticatedContentRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
  AuthenticatedAdminLifetimeRoute: AuthenticatedAdminLifetimeRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedEventsIdEditRoute: AuthenticatedEventsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StoreRouteChildren {
  StoreIdRoute: typeof StoreIdRoute
  StoreSubscribeRoute: typeof StoreSubscribeRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreIdRoute: StoreIdRoute,
  StoreSubscribeRoute: StoreSubscribeRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  StoreRoute: StoreRouteWithChildren,
  UnlockRoute: UnlockRoute,
  EventsIdRoute: EventsIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
